# mlops/feature-store/feast/feature_store.yaml

# Feast Feature Store Configuration for Goat Prediction Ultimate
# Complete feature store setup with multi-sport support, real-time features, and production-grade configuration

# Project Configuration
project: goat_prediction_feature_store
registry: data/registry.db
provider: aws  # Options: local, gcp, aws, azure

# Online Store Configuration
online_store:
  # AWS DynamoDB (Production)
  type: dynamodb
  region: ${AWS_REGION:-eu-west-1}
  billing_mode: PAY_PER_REQUEST
  tags:
    Project: goat-prediction
    Environment: ${ENVIRONMENT:-production}
    Team: ml-engineering
  
  # For local development
  local:
    type: redis
    connection_string: "localhost:6379,db=0"
    ssl: false
    
  # Performance settings
  write_concurrency: 10
  read_concurrency: 50
  batch_size: 1000
  ttl_seconds: 86400  # 24 hours

# Offline Store Configuration
offline_store:
  # AWS S3 (Production)
  type: s3
  bucket: goat-prediction-feature-store-${ENVIRONMENT}
  region: ${AWS_REGION:-eu-west-1}
  endpoint_url: null  # Use default AWS endpoints
  s3_endpoint_override: null
  
  # Partitioning strategy
  partition_by:
    - date
    - sport
    - league
    
  # File format settings
  file_format: parquet
  compression: snappy
  encryption: sse-s3
  
  # For local development
  local:
    type: file
    path: data/offline_store

# Batch Engine Configuration
batch_engine:
  # Spark Configuration
  spark:
    enabled: true
    master: ${SPARK_MASTER:-local[*]}
    config:
      spark.app.name: "goat-prediction-feature-store"
      spark.executor.memory: "4g"
      spark.driver.memory: "2g"
      spark.sql.shuffle.partitions: "200"
      spark.default.parallelism: "100"
      spark.serializer: "org.apache.spark.serializer.KryoSerializer"
      
  # Dask Configuration (alternative)
  dask:
    enabled: false
    scheduler: distributed
    workers: 4
    threads_per_worker: 2
    memory_limit: "2GB"

# Streaming Configuration
streaming:
  enabled: true
  
  # Kafka Integration
  kafka:
    bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS:-localhost:9092}
    group_id: feast-feature-store
    auto_offset_reset: latest
    enable_auto_commit: true
    security_protocol: SASL_SSL
    sasl_mechanism: SCRAM-SHA-512
    
  # Schema Registry
  schema_registry:
    url: ${SCHEMA_REGISTRY_URL:-http://localhost:8081}
    subject_suffix: -value
    
  # Processing Configuration
  processing:
    window_type: tumbling
    window_size_seconds: 60
    watermark_seconds: 10
    checkpoint_location: s3://goat-prediction-checkpoints/feast/
    
  # Sources
  sources:
    - name: live_odds_stream
      topic: live.odds
      value_schema: odds_schema.avsc
      
    - name: match_events_stream
      topic: match.events
      value_schema: events_schema.avsc
      
    - name: player_stats_stream
      topic: player.stats
      value_schema: stats_schema.avsc

# Feature Server Configuration
feature_server:
  enabled: true
  host: 0.0.0.0
  port: 6566
  workers: 4
  enable_ssl: true
  ssl_certfile: /etc/ssl/certs/goat-prediction.crt
  ssl_keyfile: /etc/ssl/private/goat-prediction.key
  
  # Authentication
  authentication:
    enabled: true
    type: jwt
    secret: ${JWT_SECRET}
    algorithm: HS256
    audience: feast-feature-server
    issuer: goat-prediction
    
  # Rate Limiting
  rate_limiting:
    enabled: true
    requests_per_second: 100
    burst_size: 50
    
  # Monitoring
  monitoring:
    prometheus_enabled: true
    endpoint: /metrics
    port: 9091
    
  # Health Checks
  health:
    endpoint: /health
    live_endpoint: /live
    ready_endpoint: /ready

# Materialization Configuration
materialization:
  # Scheduled Materialization
  scheduler:
    enabled: true
    type: airflow  # Options: airflow, argo, github_actions
    interval_minutes: 30
    start_date: "2024-01-01T00:00:00"
    timezone: UTC
    
  # Incremental Materialization
  incremental:
    enabled: true
    lookback_days: 7
    batch_size_days: 1
    
  # TTL Settings
  ttl:
    online_store_days: 30
    offline_store_days: 365
    registry_days: 730
    
  # Resource Configuration
  resources:
    cpu: "2"
    memory: "4Gi"
    max_workers: 5
    timeout_minutes: 60

# Feature Validation
validation:
  enabled: true
  
  # Data Quality Rules
  rules:
    - name: feature_freshness
      severity: error
      condition: "age_hours < 24"
      
    - name: completeness
      severity: warning
      condition: "completeness_ratio > 0.95"
      
    - name: value_range
      severity: error
      condition: "min >= 0 AND max <= 1"
      
    - name: uniqueness
      severity: warning
      condition: "duplicate_ratio < 0.01"
  
  # Great Expectations Integration
  great_expectations:
    enabled: true
    expectation_suite_name: feature_store_suite
    data_context_root_dir: ./great_expectations
    
  # Monitoring
  monitoring:
    slack_webhook: ${SLACK_VALIDATION_WEBHOOK}
    email_recipients:
      - data-engineering@goat-prediction.com
      - ml-ops@goat-prediction.com

# Feature Repository Configuration
repo_config:
  # Paths
  feature_repo: "feature_repo/"
  test_repo: "tests/feature_repo/"
  
  # Git Integration
  git:
    enabled: true
    repo_url: "https://github.com/goat-prediction/feature-store.git"
    branch: main
    sync_interval_minutes: 5
    
  # Versioning
  versioning:
    enabled: true
    strategy: semantic
    auto_increment_patch: true
    
  # Testing
  testing:
    pytest_path: "tests/"
    coverage_threshold: 0.8
    integration_tests: true
    performance_tests: true

# Entity Configuration
entities:
  # Core Entities
  match:
    description: "Sports match entity"
    join_keys: ["match_id"]
    value_type: STRING
    tags:
      - core
      - sports
      
  team:
    description: "Team entity"
    join_keys: ["team_id"]
    value_type: STRING
    tags:
      - core
      - sports
      
  player:
    description: "Player entity"
    join_keys: ["player_id"]
    value_type: STRING
    tags:
      - core
      - sports
      
  league:
    description: "League entity"
    join_keys: ["league_id"]
    value_type: STRING
    tags:
      - core
      - sports
      
  # Time-based Entities
  event_timestamp:
    description: "Event timestamp"
    join_keys: ["event_timestamp"]
    value_type: UNIX_TIMESTAMP
    tags:
      - temporal
      
  created_timestamp:
    description: "Feature creation timestamp"
    join_keys: ["created_timestamp"]
    value_type: UNIX_TIMESTAMP
    tags:
      - temporal
      - metadata

# Feature View Configuration
feature_views:
  # Football Feature Views
  football_match_stats:
    entities: [match, team]
    ttl: 86400
    online: true
    tags:
      - football
      - match_stats
      
  football_team_form:
    entities: [team, league]
    ttl: 259200  # 3 days
    online: true
    tags:
      - football
      - team_form
      
  football_player_performance:
    entities: [player, team]
    ttl: 172800  # 2 days
    online: true
    tags:
      - football
      - player_stats
      
  # Basketball Feature Views
  basketball_game_stats:
    entities: [match, team]
    ttl: 86400
    online: true
    tags:
      - basketball
      - game_stats
      
  basketball_team_momentum:
    entities: [team, league]
    ttl: 172800
    online: true
    tags:
      - basketball
      - team_momentum
      
  # Tennis Feature Views
  tennis_match_stats:
    entities: [match, player]
    ttl: 86400
    online: true
    tags:
      - tennis
      - match_stats
      
  tennis_player_form:
    entities: [player]
    ttl: 259200
    online: true
    tags:
      - tennis
      - player_form
      
  # Esports Feature Views
  esports_match_stats:
    entities: [match, team]
    ttl: 86400
    online: true
    tags:
      - esports
      - match_stats
      
  esports_team_composition:
    entities: [team, player]
    ttl: 172800
    online: true
    tags:
      - esports
      - team_composition

# Data Sources Configuration
data_sources:
  # Batch Sources
  football_matches_batch:
    type: parquet
    path: s3://goat-prediction-data/football/matches/
    event_timestamp_column: "match_date"
    created_timestamp_column: "created_at"
    field_mapping:
      match_id: "match_id"
      home_team_id: "home_team_id"
      away_team_id: "away_team_id"
      
  basketball_games_batch:
    type: parquet
    path: s3://goat-prediction-data/basketball/games/
    event_timestamp_column: "game_date"
    created_timestamp_column: "created_at"
    
  tennis_matches_batch:
    type: parquet
    path: s3://goat-prediction-data/tennis/matches/
    event_timestamp_column: "match_date"
    created_timestamp_column: "created_at"
    
  # Streaming Sources
  live_odds_stream:
    type: kafka
    bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic: live.odds
    message_format: "avro"
    watermark_delay_threshold: "10s"
    
  match_events_stream:
    type: kafka
    bootstrap_servers: ${KAFKA_BOOTSTRAP_SERVERS}
    topic: match.events
    message_format: "avro"
    watermark_delay_threshold: "5s"
    
  # Database Sources
  postgres_sports_db:
    type: postgres
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    database: sports
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    sslmode: require
    
  # API Sources
  sports_api:
    type: http
    endpoint: ${SPORTS_API_ENDPOINT}
    headers:
      Authorization: "Bearer ${SPORTS_API_KEY}"
      Content-Type: "application/json"
    format: json
    polling_interval_seconds: 60

# Feature Definitions (Simplified - Actual features in Python files)
features:
  # Football Features
  football:
    match_level:
      - home_team_win_rate_last_5
      - away_team_win_rate_last_5
      - home_team_goals_scored_avg
      - away_team_goals_conceded_avg
      - h2h_home_wins_last_10
      
    team_level:
      - form_points_last_5_matches
      - home_advantage_index
      - injury_impact_score
      - squad_rotation_factor
      
    player_level:
      - player_form_rating
      - goals_per_match_avg
      - expected_goals_avg
      - assists_per_match_avg
      
  # Basketball Features
  basketball:
    game_level:
      - home_team_win_percentage
      - away_team_win_percentage
      - point_spread_avg
      - total_points_avg
      
    team_level:
      - offensive_rating_last_5
      - defensive_rating_last_5
      - pace_factor
      - turnover_percentage
      
  # Common Features
  common:
    temporal:
      - day_of_week_sin
      - day_of_week_cos
      - month_sin
      - month_cos
      - hour_of_day_sin
      - hour_of_day_cos
      
    weather:
      - temperature_celsius
      - precipitation_mm
      - humidity_percentage
      - wind_speed_kph
      
    venue:
      - stadium_capacity
      - pitch_condition_index
      - altitude_meters
      - travel_distance_km

# Monitoring and Observability
monitoring:
  # Metrics Collection
  metrics:
    feast_metrics: true
    custom_metrics: true
    export_to_prometheus: true
    
  # Logging
  logging:
    level: INFO
    format: json
    output:
      - file: /var/log/feast/feast.log
      - stdout
      
  # Alerting
  alerting:
    enabled: true
    channels:
      slack: ${SLACK_ALERT_WEBHOOK}
      pagerduty: ${PAGERDUTY_INTEGRATION_KEY}
      email: data-alerts@goat-prediction.com
      
    thresholds:
      materialization_failure_rate: 0.05
      online_store_latency_p95_ms: 100
      feature_freshness_hours: 24
      
  # Tracing
  tracing:
    enabled: true
    provider: jaeger
    endpoint: ${JAEGER_ENDPOINT}
    sampling_rate: 0.1

# Security Configuration
security:
  # Authentication
  authentication:
    enabled: true
    providers:
      - type: oauth2
        issuer: ${OAUTH_ISSUER}
        audience: ${OAUTH_AUDIENCE}
        
      - type: api_key
        header: X-API-Key
        
  # Authorization
  authorization:
    enabled: true
    rbac:
      enabled: true
      roles:
        - admin
        - data_scientist
        - data_engineer
        - read_only
        
  # Encryption
  encryption:
    at_rest:
      enabled: true
      kms_key_id: ${AWS_KMS_KEY_ID}
      
    in_transit:
      enabled: true
      tls_version: "TLSv1.3"
      
  # Compliance
  compliance:
    gdpr_compliant: true
    data_retention_days: 365
    audit_logging: true

# Performance Optimization
performance:
  # Caching
  caching:
    enabled: true
    type: redis
    ttl_seconds: 300
    max_size_mb: 1024
    
  # Indexing
  indexing:
    enabled: true
    index_columns:
      - match_id
      - team_id
      - event_timestamp
      - sport_type
      
  # Query Optimization
  query_optimization:
    predicate_pushdown: true
    column_pruning: true
    partition_pruning: true
    join_reordering: true
    
  # Resource Management
  resources:
    max_materialization_workers: 10
    max_online_read_qps: 1000
    max_offline_read_parallelism: 20

# Backup and Disaster Recovery
backup:
  enabled: true
  
  # Backup Schedule
  schedule:
    frequency: daily
    retention_days: 30
    full_backup_frequency: weekly
    
  # Backup Locations
  locations:
    - type: s3
      bucket: goat-prediction-backups-feast
      path: feast/
      region: ${AWS_BACKUP_REGION}
      
    - type: gcs
      bucket: goat-prediction-backups-feast
      path: feast/
      
  # Recovery
  recovery:
    point_in_time_recovery: true
    rto_hours: 4  # Recovery Time Objective
    rpo_hours: 1  # Recovery Point Objective

# Environment-Specific Configuration
environments:
  development:
    online_store:
      type: redis
      connection_string: "localhost:6379"
      
    offline_store:
      type: file
      path: "./data/offline_store_dev"
      
    monitoring:
      level: DEBUG
      
  staging:
    online_store:
      type: dynamodb
      table_prefix: "staging_"
      
    offline_store:
      type: s3
      bucket: "goat-prediction-feature-store-staging"
      
  production:
    online_store:
      type: dynamodb
      billing_mode: PROVISIONED
      read_capacity_units: 100
      write_capacity_units: 50
      
    offline_store:
      type: s3
      bucket: "goat-prediction-feature-store-production"
      
    security:
      authentication:
        required: true
        
    monitoring:
      alerting:
        enabled: true

# Integration with ML Ecosystem
integrations:
  # MLflow Integration
  mlflow:
    enabled: true
    tracking_uri: ${MLFLOW_TRACKING_URI}
    registry_uri: ${MLFLOW_REGISTRY_URI}
    
  # Kubeflow Integration
  kubeflow:
    enabled: true
    pipeline_root: ${KUBEFLOW_PIPELINE_ROOT}
    
  # Airflow Integration
  airflow:
    enabled: true
    dag_id: feast_materialization_dag
    schedule_interval: "*/30 * * * *"
    
  # Data Version Control (DVC)
  dvc:
    enabled: true
    remote: s3://goat-prediction-dvc/feast
    
  # Monitoring Tools
  monitoring_tools:
    datadog:
      enabled: true
      api_key: ${DATADOG_API_KEY}
      
    newrelic:
      enabled: false
      
    splunk:
      enabled: true
      hec_token: ${SPLUNK_HEC_TOKEN}
      hec_url: ${SPLUNK_HEC_URL}

# Documentation and Metadata
documentation:
  # Feature Documentation
  feature_docs:
    enabled: true
    format: markdown
    output_dir: docs/features/
    
  # Data Dictionary
  data_dictionary:
    enabled: true
    include:
      - description
      - data_type
      - value_range
      - null_percentage
      - example_values
      
  # Lineage Tracking
  lineage:
    enabled: true
    capture_sql: true
    capture_operations: true
    
  # Change Log
  changelog:
    enabled: true
    auto_generate: true

# Templates and Macros
templates:
  # Environment Variable Substitution
  env_substitution: true
  
  # Jinja2 Templates for Dynamic Configuration
  jinja2:
    enabled: true
    variables:
      environment: ${ENVIRONMENT}
      sport: ${SPORT}
      date: "{{ now().strftime('%Y-%m-%d') }}"
      
  # Feature Generation Templates
  feature_templates:
    rolling_window:
      template: |
        {{ feature_name }}_last_{{ window }}_matches
      parameters:
        window: [5, 10, 20]
        
    moving_average:
      template: |
        {{ feature_name }}_ma_{{ window }}
      parameters:
        window: [3, 5, 7, 10]

# Deployment Configuration
deployment:
  # Infrastructure as Code
  terraform:
    enabled: true
    module_path: infrastructure/feast/
    
  # Kubernetes
  kubernetes:
    enabled: true
    namespace: feast
    helm_chart:
      repository: https://feast-helm.github.io/charts
      chart: feast
      version: 0.30.0
      
  # CI/CD
  ci_cd:
    github_actions:
      workflow: .github/workflows/feast.yml
      on:
        push:
          paths:
            - 'feature_repo/**'
            - 'feature_store.yaml'
            
    gitlab_ci:
      enabled: false
      
  # Rollout Strategy
  rollout:
    strategy: canary
    initial_traffic_percentage: 10
    evaluation_period_hours: 24
    metrics:
      - online_store_availability
      - feature_retrieval_latency
      - data_freshness

# Support and Maintenance
support:
  # Maintenance Windows
  maintenance:
    schedule: "Sunday 02:00-04:00 UTC"
    auto_apply_updates: false
    
  # Support Contacts
  contacts:
    primary: ml-ops@goat-prediction.com
    secondary: data-engineering@goat-prediction.com
    emergency: oncall-ml@goat-prediction.com
    
  # SLAs
  slas:
    availability: 99.95%
    latency_p95_ms: 100
    data_freshness_hours: 1
    support_response_hours: 2

# Notes and Comments
_notes: |
  # Feast Feature Store Configuration
  # Goat Prediction Ultimate - Production Grade
  
  ## Key Features:
  1. Multi-sport feature management
  2. Real-time streaming support
  3. Production-grade security
  4. Comprehensive monitoring
  5. Disaster recovery
  
  ## Environment Variables Required:
  - AWS_REGION: AWS region for resources
  - ENVIRONMENT: dev/staging/prod
  - KAFKA_BOOTSTRAP_SERVERS: Kafka brokers
  - POSTGRES_HOST: Database host
  
  ## Usage:
  1. Apply environment variables
  2. Initialize: feast init --template aws
  3. Apply: feast apply
  4. Materialize: feast materialize-incremental $(date -u +%Y-%m-%d)
  
  ## Support:
  - Documentation: https://docs.goat-prediction.com/feature-store
  - Slack: #feature-store-support
  - Email: feature-store@goat-prediction.com
  
  ## Version: 2.0.0
  ## Last Updated: 2024-01-01
  ## Maintainer: ML Engineering Team
